# Bath Tub Part
cvrg_file_paths:
  {
    # path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/bath_tub_task1.csv"], /],
    path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/bath_tub_task2.csv"], /],
    # path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/bath_tub_task3.csv"], /],
    # path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/bath_tub_task4.csv"], /],
    cvrg_path: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/waypoints.csv"], /], # Path to save the path
    success_flags: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/success_flags.csv"], /], # Path to save the path
    joint_states: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/joint_states.csv"], /], # Path to save the trajectory
    mesh_path: !!python/object/apply:string.join [[$(arg pkg_path),"data/meshes/bath_tub.stl"], /],
    mesh_viz_path: "package://pct/data/meshes/bath_tub.stl",
  }

cvrg_tf_param:
    {
        # world_T_part: [1,0,0,0,0,1.57], # x,y,z,rx,ry,rz xyzbxbybz
        world_T_part: [1,0,0,0,0,-1.57], # x,y,z,rx,ry,rz Task1
        # world_T_part: [1.1,0,0,0,0,1.57], # x,y,z,rx,ry,rz Task4
    }

viz_param:
    {
        rob_speed: 100
    }

gen_path: false
rob_config: [0,0,0,0,0,0]
sampling_res: 20 # Degrees