# All transforms are x,y,z,rx,ry,rz
tool_name: "ferro_sander"
world_T_tool: [0,0,0,0,0,0]

ferro_sander:
  {
    ff_T_tool: [0.0,0,0.2893,0,0,0, # Original TCP at center
                5.000000e-02, 0, 2.893000e-01, 0, 0, 0,
                4.330127e-02, 2.500000e-02, 2.893000e-01, 0, 0, 0,
                2.500000e-02, 4.330127e-02, 2.893000e-01, 0, 0, 0,
                3.061617e-18, 5.000000e-02, 2.893000e-01, 0, 0, 0,
                -2.500000e-02, 4.330127e-02, 2.893000e-01, 0, 0, 0,
                -4.330127e-02, 2.500000e-02, 2.893000e-01, 0, 0, 0,
                -5.000000e-02, 6.123234e-18, 2.893000e-01, 0, 0, 0,
                -4.330127e-02, -2.500000e-02, 2.893000e-01, 0, 0, 0,
                -2.500000e-02, -4.330127e-02, 2.893000e-01, 0, 0, 0,
                -9.184851e-18, -5.000000e-02, 2.893000e-01, 0, 0, 0,
                2.500000e-02, -4.330127e-02, 2.893000e-01, 0, 0, 0,
                4.330127e-02, -2.500000e-02, 2.893000e-01, 0, 0, 0], # All plus and minus Y TCPs 
    tool_stl_path: !!python/object/apply:string.join [[$(arg pkg_path), "data/meshes/ferro_sander.stl"], /],
    tool_stl_coll_path: !!python/object/apply:string.join [[$(arg pkg_path), "data/meshes/coll/ferro_sander/ferro_sander.stl"], /],
    tool_stl_coll_folder: !!python/object/apply:string.join [[$(arg pkg_path), "data/meshes/coll/ferro_sander"], /],
    tool_stl_viz_path: "package://pct/data/meshes/ferro_sander.stl",
    # Override
    # ff_T_tool: [0.0,0,0.2893,0,0,0] # Original TCP at center. Overriding multiple tcps
  }