# Gear Internal Part
cvrg_file_paths:
    {
    # path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/gear_ext_deburring.csv"], /],
    # path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/gear_int_inner_test_edge_chamfering.csv"], /],
    path_file: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/gear_int.csv"], /],
    cvrg_path: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/waypoints.csv"], /], # Path to save the path
    success_flags: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/success_flags.csv"], /], # Path to save the path
    joint_states: !!python/object/apply:string.join [[$(arg pkg_path),"data/csv/joint_states.csv"], /], # Path to save the trajectory
    mesh_path: !!python/object/apply:string.join [[$(arg pkg_path),"data/meshes/gear_int.stl"], /],
    mesh_viz_path: "package://pct/data/meshes/gear_int.stl",
    }

cvrg_tf_param:
    {
        world_T_part: [0.8,0,0.7,0,0,0], # x,y,z,rx,ry,rz xyzbxbybz
    }

viz_param:
    {
        rob_speed: 10
    }

gen_path: false
rob_config: [0,0,0,0,0,0]
sampling_res: 20 # Degrees
# The first two values in tolerances are angle
# theta1 and theta2 bounds
# Three bounds in total for X Y and Z
tolerances: [ -50,50,-50,50,-100,100 ]
max_itr: 1
tol_constraint: 1.0
opt_cost: 5.29
# opt_trigger: 0.07
opt_trigger: 1.0
alpha: 10
neigh_thrld: 0.2
k: 10