# All transforms are x,y,z,rx,ry,rz

ferro_sander:
  {
    ff_T_tool: [0.0,0,0.2893,0,0,0, # Original TCP at center
                0.01,0,0.2893,0,0,0,
                0.02,0,0.2893,0,0,0,
                0.03,0,0.2893,0,0,0,
                0.04,0,0.2893,0,0,0,
                0.05,0,0.2893,0,0,0,
                -0.01,0,0.2893,0,0,0,
                -0.02,0,0.2893,0,0,0,
                -0.03,0,0.2893,0,0,0,
                -0.04,0,0.2893,0,0,0,
                -0.05,0,0.2893,0,0,0, # All plus and minus X TCPs
                0.0,0.01,0.2893,0,0,0,
                0.0,0.02,0.2893,0,0,0,
                0.0,0.03,0.2893,0,0,0,
                0.0,0.04,0.2893,0,0,0,
                0.0,0.05,0.2893,0,0,0,
                0.0,-0.01,0.2893,0,0,0,
                0.0,-0.02,0.2893,0,0,0,
                0.0,-0.03,0.2893,0,0,0,
                0.0,-0.04,0.2893,0,0,0,
                0.0,-0.05,0.2893,0,0,0], # All plus and minus Y TCPs 
    tool_stl_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/ferro_sander.stl",
    tool_stl_viz_path: "package://pct/data/meshes/ferro_sander.stl",
    tool_stl_coll_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/ferro_sander/ferro_sander_coll.stl",
    tool_stl_coll_folder: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/ferro_sander",
    # Override
    ff_T_tool: [0.0,0,0.2893,0,0,0] # Original TCP at center. Overriding multiple tcps
  }

sander_v1:
  {
    tool_stl_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/sander_v1.stl",
    tool_stl_coll_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/sander_v1/sander_v1_coll.stl",
    tool_stl_coll_folder: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/sander_v1",
    ff_T_tool: [0,-0.215,0.2155,0,0,0]
  }


sander:
  {
    ff_T_tool: [-0.0327, -0.0054, 0.1383, 0.0100, -0.0002, 3.1000]
  }


flange:
  {
    ff_T_tool: [0,0,0,0,0,0]
  }

wld_gun:
  {
    tool_stl_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/wld_gun.stl",
    tool_stl_coll_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/wld_gun/wld_gun.stl",
    tool_stl_coll_folder: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/wld_gun",
    ff_T_tool: [ -0.033,0.0,0.4932,0.0,0.533,0.0 ]
  }

cam_sander_0:
  {
    tool_stl_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/cam_sander_0.stl",
    tool_stl_coll_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/cam_sander_0/cam_sander_0.stl",
    tool_stl_coll_folder: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/cam_sander_0",
    ff_T_tool: [ 0.00565,-0.1463,0.30661,0.0,0.0,0.0 ] 
  }

cam_sander_90:
  {
    tool_stl_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/cam_sander_90.stl",
    tool_stl_coll_path: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/cam_sander_90/cam_sander_90s.stl",
    tool_stl_coll_folder: "/home/rmalhan/Work/USC/Modules/cartesian_planning/cartesian_planner/src/pct/data/meshes/coll/cam_sander_90",
    ff_T_tool: [ 0.0873,-0.24201,0.027,1.57,0.0,3.14 ] 
  }